image: python:3.10-bullseye

stages:
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

build-draft:
  stage: build
  script:
    - echo "Building draft version"
    - teachbooks build book/ > >(tee stdout.log) 2> >(tee stderr.log >&2)
  artifacts:
    paths:
      - book/_build/html
      - stdout.log
      - stderr.log
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: always

build-production:
  stage: build
  script:
    - echo "Building production version"
    - teachbooks build --publish book/ > >(tee stdout.log) 2> >(tee stderr.log >&2)
  artifacts:
    paths:
      - book/_build/html
      - stdout.log
      - stderr.log
  rules:
    - if: $CI_COMMIT_BRANCH == "publish"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "publish"
      when: always

deploy-draft:
  stage: deploy
  needs: ["build-draft"]
  script:
    - |
      curl -X POST https://mude.citg.tudelft.nl/hooks/book-deploy-draft \
        -H "Content-Type: application/json" \
        -H "X-Gitlab-Token: glpat-m4CzsDqHnXNn3Pf5Whyd" \
        -d '{
          "object_kind": "pipeline",
          "object_attributes": {
            "status": "success",
            "ref": "main"
          }
        }'
  environment:
    name: draft
    url: https://mude.citg.tudelft.nl/2024/book/draft
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: always

deploy-production:
  stage: deploy
  needs: ["build-production"]
  script:
    - |
      curl -X POST https://mude.citg.tudelft.nl/hooks/book-deploy \
        -H "Content-Type: application/json" \
        -H "X-Gitlab-Token: glpat-m4CzsDqHnXNn3Pf5Whyd" \
        -d '{
          "object_kind": "pipeline",
          "object_attributes": {
            "status": "success",
            "ref": "publish"
          }
        }'
  environment:
    name: production
    url: https://mude.citg.tudelft.nl/2024/book
  rules:
    - if: $CI_COMMIT_BRANCH == "publish"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "publish"
      when: always