build-and-deploy:
  stage: build
  script:
    # Debug info before build
    - echo "Starting build process..."
    - df -h
    - pwd
    - ls -la

    # Build the book based on branch
    - |
      if [ "$CI_COMMIT_BRANCH" == "release" ]; then
        echo "Building production version"
        teachbooks build --publish book/ > >(tee stdout.log) 2> >(tee stderr.log >&2)
        HOOK_URL="https://mude.citg.tudelft.nl/hooks/book-deploy-production"
      else
        echo "Building draft version"
        teachbooks build book/ > >(tee stdout.log) 2> >(tee stderr.log >&2)
        HOOK_URL="https://mude.citg.tudelft.nl/hooks/book-deploy-draft"
      fi

    # Get build size and handle deployment
    - echo "Calculating build size..."
    - SIZE=$(du -sk book/_build/html | cut -f1)
    - echo "Build size is ${SIZE}KB"
    - echo $CI_JOB_ID > build_job_id.txt
    
    # For large builds, create minimal artifact set
    - |
      if [ "$SIZE" -gt 153600 ]; then  # 150MB in KB
        echo "Build size too large, creating minimal artifact set"
        mkdir -p minimal_artifact
        cp build_job_id.txt minimal_artifact/
        cp stdout.log minimal_artifact/
        cp stderr.log minimal_artifact/
        # Signal that we're using minimal artifacts
        touch USE_MINIMAL_ARTIFACTS
      fi

    # Always proceed with deployment notification
    - |
      curl -X POST "${HOOK_URL}" \
        -H "Content-Type: application/json" \
        -H "X-Gitlab-Token: glpat-m4CzsDqHnXNn3Pf5Whyd" \
        -d "{\"object_kind\":\"pipeline\",\"object_attributes\":{\"status\":\"success\",\"ref\":\"${CI_COMMIT_BRANCH}\"},\"build_job_id\":$CI_JOB_ID}"

    # Debug info after build
    - echo "Directory sizes after build:"
    - du -sh book/_build/*
    - echo "Build and deploy completed"

  artifacts:
    when: on_success
    paths:
      - stdout.log
      - stderr.log
      - build_job_id.txt
      - USE_MINIMAL_ARTIFACTS
      - minimal_artifact/
      - book/_build/html/**
    exclude:
      - book/_build/html/** 
      - book/_build/jupyter_execute/**
      - "**/*.ipynb"
      - "**/__pycache__"
      - "**/*.pyc"
      - book/_build/.doctrees
      - book/_build/jupyter_cache
      - book/_build/.jupyter_cache
      - book/_build/*.pickle
      - book/_build/*.doctree
      - "**/*.pickle"
      - "**/*.doctree"
      - "**/*.ipynb_checkpoints"
    expire_in: 1 week

  environment:
    name: $CI_COMMIT_BRANCH
    url: $CI_ENVIRONMENT_URL

  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        CI_ENVIRONMENT_URL: "https://mude.citg.tudelft.nl/2024/book/draft"
    - if: $CI_COMMIT_BRANCH == "release"
      variables:
        CI_ENVIRONMENT_URL: "https://mude.citg.tudelft.nl/2024/book"