services:
  web:
    container_name: mude-book
    build:
        context: ${PWD}
        dockerfile: ${PWD}/docker/Dockerfile
    ports:
     - "8000:8000"
    volumes:
      - type: bind
        source: ${PWD}
        target: /book
    command: $START_SERVER
    stdin_open: true 
    tty: true
