title: MUDE
author: MUDE Teachers and the Student Army
logo: _static/MUDE_Logo-small.png

execute:
  execute_notebooks: auto
  exclude_patterns:
    - '*_dont_execute.ipynb'

sphinx:
  config:
    # Bibliography style
    bibtex_reference_style: author_year
  extra_extensions:
  - sphinx_inline_tabs
  - sphinx_grasple
  - sphinx.ext.imgconverter

bibtex_bibfiles:
  - _bibliography/references_pd.bib
  
launch_buttons:
  thebe: true
  
repository:
  url: https://gitlab.tudelft.nl/mude/book  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)
